
SELECT 'DEPARTMENTS' AS Table_Name, COUNT(*) AS Record_Count FROM DEPARTMENTS
UNION SELECT 'DESIGNATIONS', COUNT(*) FROM DESIGNATIONS
UNION SELECT 'POSTAL_CODES', COUNT(*) FROM POSTAL_CODES
UNION SELECT 'EMPLOYEES', COUNT(*) FROM EMPLOYEES
UNION SELECT 'ADDRESSES', COUNT(*) FROM ADDRESSES
UNION SELECT 'USERS', COUNT(*) FROM USERS
UNION SELECT 'TRAINING_ASSIGNMENTS', COUNT(*) FROM TRAINING_ASSIGNMENTS;

SELECT employee_id, first_name, last_name, email, employment_type 
FROM EMPLOYEES 
WHERE employee_code IS NULL OR join_date IS NULL;

SELECT a.address_id, a.employee_id, e.first_name, e.last_name 
FROM ADDRESSES a
LEFT JOIN EMPLOYEES e ON a.employee_id = e.employee_id
WHERE e.employee_id IS NULL;